### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by berlin0613** [HuJianChong/MyWanAndroid#3]
这个框架不成熟，有一个致命的bug，就是在使用google navigation的时候，会出现activity为null的空指针异常

**Comment by HuJianChong** [comment]
能贴一下报错信息么，我的项目里面没用到google navigation

**Comment by HuJianChong** [comment]
今天修复了，感谢提出问题

> 这个框架不成熟，有一个致命的bug，就是在使用google navigation的时候，会出现activity为null的空指针异常
