### ISSUE TITLE
AndroidStudio用的那个版本啊？AndroidStudio Giraffe 2022.3.1会报错

### ISSUE THREAD

**Issue by wv1124** [HuJianChong/MyWanAndroid#4]
ArticleAdapter.kt: (7, 27): Unresolved reference: databinding

**Comment by HuJianChong** [comment]
那是因为你改了包名，修改包名后，需要把文件路径都改动一下

**Comment by HuJianChong** [comment]
> ArticleAdapter.kt: (7, 27): Unresolved reference: databinding

需要文件夹名要对应修改 namespace
