### ISSUE TITLE
failCallback返回的时候能取BaseData的数据吗？

### ISSUE THREAD

**Issue by xfy-c** [HuJianChong/MyWanAndroid#5]
有时候会遇到一些特殊的需求，请求失败后，要拿到code做其他操作，或者根据code提示信息跳转其他页面

**Comment by HuJianChong** [comment]
可以直接在需要的地方重写requestDataWithFlow

把这一句改一下，不只传msg，而传整个data
ReqState.Error -> baseData.msg?.let { error(it) }
